kind: pipeline
type: docker
name: packmaker

steps:
- name: lock
  image: kalka/packmaker
  commands:
  - python -VVV
  - pip install aiohttp[speedups]
  - curl -L 'https://get.kalka.io/curseforge.db' > curseforge.db
  - packmaker -vvvv lock
- name: package
  image: kalka/packmaker
  commands:
  - zip -r Wolfpack-Legacy.zip .minecraft update.py update.bat instance.cfg mmc-pack.json
  - zip -r config.zip .minecraft mmc-pack.json
 - name: mod-list
   image: python
   commands:
   - python -VVV
   - pip install aiohttp[speedups]
   - pip install urllib3
   - python raw_mod_list.py
- name: upload
  image: plugins/gitea-release
  settings:
    api_key:
      from_secret: api_key
    base_url: https://git.kalka.io
    title: ${DRONE_TAG}
    note: ${DRONE_COMMIT_MESSAGE}
    files:
      - Wolfpack-Legacy.zip
      - config.zip
      - packmaker.lock
      - modlist.db
  when:
    event: tag

    